name: NBC Ministries
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00abaf'
    - '#004389'
    - '#fbf9fa'
    - '#9cbac0'
    - '#5184b1'
  brandStrength: 0.9775159957353026
  lightness: 0.6124858071561903
  saturation: 0.14871289068832994
  rhythmicContrast: 0.44871759228408337
purpose: []
